//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJUSTE
    {
        public string RAZON { get; set; }
        public decimal PESO_AJUSTE { get; set; }
        public string MOVIMIENTO_A { get; set; }
        public decimal ID_AJUSTE { get; set; }
        public int ID_STOCK { get; set; }
        public Nullable<System.DateTime> Fecha_Ajuste { get; set; }
    
        public virtual STOCK STOCK { get; set; }
    }
}
