//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public decimal ID_CONTACTOS { get; set; }
        public string CEDULA { get; set; }
        public Nullable<decimal> TELEFONO_HAB { get; set; }
        public Nullable<decimal> TELEFONO_PERS { get; set; }
        public string EMAIL { get; set; }
    
        public virtual SOCIO_NEGOCIO SOCIO_NEGOCIO { get; set; }
    }
}
