//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDENCIALE
    {
        public string ID_Usuario { get; set; }
        public string CLAVE { get; set; }
        public string ROL { get; set; }
        public string ESTADO { get; set; }
        public string Nombre_usuario { get; set; }
    }
}
