//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMCRLEntities : DbContext
    {
        public AMCRLEntities()
            : base("name=AMCRLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AJUSTE> AJUSTEs { get; set; }
        public virtual DbSet<BODEGA> BODEGAs { get; set; }
        public virtual DbSet<COMPRA> COMPRAs { get; set; }
        public virtual DbSet<CONTACTO> CONTACTOS { get; set; }
        public virtual DbSet<CREDENCIALE> CREDENCIALES { get; set; }
        public virtual DbSet<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        public virtual DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<MATERIAL> MATERIALs { get; set; }
        public virtual DbSet<MONEDA> MONEDAs { get; set; }
        public virtual DbSet<SOCIO_NEGOCIO> SOCIO_NEGOCIO { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<VENTA> VENTAs { get; set; }
    }
}
