//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public decimal COD_VENTA { get; set; }
        public string CEDULA { get; set; }
        public decimal ID_BODEGA { get; set; }
        public string ID_MONEDA { get; set; }
        public Nullable<decimal> MONTO_TOTAL_V { get; set; }
        public Nullable<System.DateTime> Fecha_Venta { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual MONEDA MONEDA { get; set; }
        public virtual SOCIO_NEGOCIO SOCIO_NEGOCIO { get; set; }
    }
}
